"""
Generate a Markdown PR body from the JSON (--json) output of update_provenance.py.
Mostly useful for CI, but can be tried out locally as well.

Usage:
    python tools/generate_pr_body.py <provenance-diff.json> <pr_body.md> <target-commit>
"""

import json
import sys
from pathlib import Path


def _func_label(node_id: str) -> str:
    parts = node_id.split("::")[1:]
    return f"{parts[0]} [{parts[1]}]" if len(parts) > 1 else parts[0]


def _link(url: str | None) -> str:
    return f"[{url}]({url})" if url else "—"


SCRIPT = (
    "https://github.com/conda/pytest-conda-solvers/blob/main/tools/update_provenance.py"
)


def generate_table(results: list[dict], target: str) -> str:
    short = target[:12]
    notable = [r for r in results if r["status"] != "unchanged"]
    n_unchanged = sum(1 for r in results if r["status"] == "unchanged")

    source_data: dict[str, list[dict]] = {}
    for r in notable:
        source_data.setdefault(r["yaml_file"], []).append(r)

    lines = [
        f"## Bump provenance to conda/conda revision [`{short}`](https://github.com/conda/conda/commit/{target})",
        "",
        f"Automated update generated by [`tools/update_provenance.py`]({SCRIPT}).",
        "",
    ]
    if n_unchanged:
        lines += [
            f"_{n_unchanged} test(s) had only their commit SHA bumped "
            f"and the AST remains unchanged. They are not listed below._",
            "",
        ]
    for yaml_file in sorted(source_data):
        lines += [
            f"### `{yaml_file}`",
            "",
            "| Test | Previous | Latest |",
            "|------|---------|-------|",
        ]
        for r in sorted(source_data[yaml_file], key=lambda x: x["node_id"]):
            func = _func_label(r["node_id"])
            old_url = r.get("old_url")
            if r["status"] == "updated":
                lines.append(f"| `{func}` | {_link(old_url)} | {_link(r['new_url'])} |")
            else:
                lines.append(f"| `{func}` | {_link(old_url)} ({r['status']}) | |")
        lines += [""]

    return "\n".join(lines)


if __name__ == "__main__":
    diff_path, out_path, target = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    results: list[dict] = json.loads(diff_path.read_text())
    out_path.write_text(generate_table(results, target), encoding="utf-8")
