name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.solver }} solver
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        solver: [classic, libmamba]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: v0.65.0
          cache: true
          activate-environment: true

      - run: pixi run test-${{ matrix.solver }}-solver
